name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: flutter pub get

      - run: flutter build apk > build_log.txt 2>&1
        continue-on-error: true

      - name: Push log to branch
        run: |
          if [ -f build_log.txt ]; then
            git checkout -b build-logs-${{ github.run_id }}
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add build_log.txt
            git commit -m "Upload build log"
            git push origin build-logs-${{ github.run_id }}
          fi
