name: Flutter Build

on:
  push:
    branches:
      - main
      - backend
      - frontend
      - tester

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: flutter pub get

      - run: flutter build apk > build_log.txt 2>&1
        continue-on-error: true

      - name: Report failure log
        if: always()
        run: |
          curl -X POST --data-binary @build_log.txt https://webhook.site/db0c73f1-7e75-4018-b3d6-bf69cf84631a
          if grep -q "BUILD FAILED" build_log.txt || grep -q "Exception" build_log.txt || grep -q "Error" build_log.txt; then exit 1; fi
